[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ghas-testing"
version = "0.1.0"
description = "GHAS Testing"
readme = "README.md"
authors = ["austimkelly"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

